version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
    depends_on:
      - server
  
  server:
    build:
      context: ./server
    ports:
      - 3005:3005
    volumes:
      - ./server:/app
